### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by katya5226** [katya5226/TCCMaterialViewer#2]
![Screenshot 2023-09-15 113436](https://github.com/katya5226/TCCMaterialViewer/assets/47118494/5598d860-72ea-43cc-8b94-26d19f0f1d3e)

- Tu sploh ne bi smelo biti gostote, za ta material ni definirana, je pa cp.
- Pri enotah na y osi je spet tisti čuden znak :)
- Zakaj se pojavlja decimalna vejica namesto pike?
- Na desni v legendi je še vedno "rho".
- Pisava in številke na oseh bi lahko bili še malenkost večji :)

**Comment by OskarKocjancic** [comment]
Glede ne definirane gostote; naredil sem tako, da če datoteka ne obstaja se nastavi na default vrednost 0
